config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'categories#index'
  # get 'categories' => 'categories#index'
  # get 'categories/new' => 'categories#new'
  # get 'categories/:id' => 'categories#show', as: 'show_category'
  # post 'categories' => 'categories#create', as: 'create_category'
  # get 'categories/:id/edit' => 'categories#edit', as: 'edit_category'
  # put 'categories/:id' => 'categories#update', as: 'update_category'
  # delete 'categories/:id' => 'categories#delete', as: 'delete_category'
  # delete 'categories/:category_id/tasks/:id' => 'tasks#delete', as: 'delete_category_task'


  resources :categories do
    resources :tasks
  end
  
  root 'categories#index'

  namespace :api do
    get '/creator-roles' => 'creator_roles#index'
    get '/creators' => 'creators#index'
    get '/developers' => 'developers#index'
    get '/games' => 'games#index'
    get '/genres' => 'genres#index'
    get '/platforms' => 'platforms#index'
    get '/publishers' => 'publishers#index'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 5 }

  has_many :tasks

  belongs_to :user
  
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :category
  belongs_to :user

  validates :task_name, presence: true
  validates :task_description, presence: true
  validates :deadline, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :categories
          has_many :tasks

end

app/controllers/api/creator_roles_controller.rb
module Api
  class CreatorRolesController < ApplicationController
    def index
      creator_roles = Rawg::Client.creator_roles

      render json: creator_roles
    end
  end
end

app/controllers/api/creators_controller.rb
module Api
  class CreatorsController < ApplicationController
    def index
      creators = Rawg::Client.creators

      render json: creators
    end
  end
end

app/controllers/api/developers_controller.rb
module Api
  class DevelopersController < ApplicationController
    def index
      developers = Rawg::Client.developers

      render json: developers
    end
  end
end

app/controllers/api/games_controller.rb
module Api
  class GamesController < ApplicationController
    def index
      games = Rawg::Client.games
      
      render json: games
    end
  end
end

app/controllers/api/genres_controller.rb
module Api
  class GenresController < ApplicationController
    def index
      genres = Rawg::Client.genres

      render json: genres
    end
  end
end

app/controllers/api/platforms_controller.rb
module Api
  class PlatformsController < ApplicationController
    def index
      genres = Rawg::Client.genres

      render json: genres
    end
  end
end

app/controllers/api/publishers_controller.rb
module Api
  class PublishersController < ApplicationController
    def index
      publishers = Rawg::Client.publishers

      render json: publishers
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!#, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    @tasks = Task.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    # @category = Category.new
    @category = current_user.categories.build
  end

  def create
    # @category = Category.new(category_params)
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path
    else :index
    end
  end

  def correct_user
    @user = User.all
    @category = current_user.categories.find_by(id: params[:id])
    redirect_to categories_path, notice: "You are not authorized to edit this category" if @category.nil?
  end

  private 
  
  def category_params
    params.require(:category).permit(:name, :description, :user_id)
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_category
  before_action :authenticate_user!

  def index
    @category_id = params[:category_id]
    @tasks = Category.find(params[:category_id]).tasks
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to category_tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to category_tasks_path(@task.category_id)
    else 
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to category_tasks_path(@task.category_id)
    else render :index
    end
  end


  private

  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:task_name, :task_description, :category_id, :deadline, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div class="card">
  <div class="card-header">
    Category Info
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= category.name %> </h5>
    <p class="card-text">
      Category ID: <%= category.id %></br>
      Category Description: <%= category.description %></br>
      Date Created: <%= category.created_at %> 
    </p>
    <%= link_to "Back", categories_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with scope: :category, model: @category, local: true do |f| %>

  <% if @category.errors.any? %>
  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
    <%end%>
  </ul>
  <%end%>

  <h1>Add New Category</h1>
  
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Category Name</label>
    <%= f.text_field :name, class: "form-control", id: "exampleInputEmail1" %>
  </div>
  
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Category Description</label>
    <%= f.text_field :description, class: "form-control", id: "exampleInputEmail1" %>
  </div>

  <p>
    <%= f.number_field :user_id, id: :category_user_id, value: current_user.id, type: :hidden %>
  </p>

  
  <p>
    <%= f.submit class: "btn btn-outline-success" %>
    <%= link_to "Cancel", categories_path, class: "btn btn-outline-secondary" %> 
  </p>
  
  <% end %>

app/views/categories/edit.html.erb
<%= form_with scope: :category, url: category_path, method: :put, local: true do |f| %>

  <% if @category.errors.any? %>
  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
    <%end%>
  </ul>
  <%end%>

  <h1>Edit Category</h1>
  
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Category Name</label>
    <%= f.text_field :name, class: "form-control", id: "exampleInputEmail1" %>
  </div>
  
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Category Name</label>
    <%= f.text_field :description, class: "form-control", id: "exampleInputEmail1" %>
  </div>
  
  <p>
    <%= f.submit class: "btn btn-outline-success" %>
  </p>

  <p>
      <%= link_to 'Cancel', categories_path, class: "btn btn-outline-secondary" %> 
  
  <% end %>

app/views/categories/index.html.erb
<div class="categories_main_container">

  <div class="col-md-8">
    <div class="row">
      <% @categories.each do |category| %>
        <% if category.user == current_user %>
          <div class="col-md-6">
            <div class="card mt-3">
              <div class="card-body">
                <h3><%= category.name %></h3>
                <%= link_to "View", category_path(category), method: :get, class: "btn btn-primary" %> 
                <%= link_to "Edit", edit_category_path(category.id), class: "btn btn-primary" %> 
                <%= link_to "Delete", category_path(category.id), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-primary" %> 
                <%= link_to "View Tasks", category_tasks_path(category.id), class: "btn btn-primary" %> 
              </div>
            </div>
          </div>
        <% end %>
      <% end %> 
    </div>
  </div>
  

  </br>
  <%= link_to "Create New Category", new_category_path, class: "btn btn-outline-success" %>
  </br>
  </br>

  <h3>Your tasks today</h3>
  <% @tasks.each do |task| %>
    <% if task.user == current_user %>
      <% if task.deadline == Date.today %>
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= task.task_name %></h5>
            <p class="card-text"><%= task.task_description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/categories/new.html.erb
<%= render"form"%>

app/views/categories/show.html.erb
<%= render @category%>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <div class="container-fluid">
  <%= link_to "Journal App", root_path, class: "navbar-brand" %>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          
        </li>
      </ul>
      <% if user_signed_in? %>
      <div class="d-flex">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.name %> <%= current_user.surname %>
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </ul>
    </li>
      </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Journal App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render "home/header" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/tasks/_task.html.erb
<div class="card">
  <div class="card-header">
    Task Info
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= task.task_name %> </h5>
    <p class="card-text">
      Task ID: <%= task.id %></br>
      Task Description: <%= task.task_description %></br>
      Date Created: <%= task.created_at %></br>
      Task Deadline: <%= task.deadline %>
    </p>
    <%= link_to "Back", category_tasks_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= form_with scope: :task, model: [@category, @task], local: true do |f| %>

  <% if @task.errors.any? %>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
    <%end%>
  </ul>
  <%end%>

  <h1>Edit Task</h1>
  
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Task Name</label>
    <%= f.text_field :task_name, class: "form-control", id: "exampleInputEmail1" %>
  </div>
  
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Task Description</label>
    <%= f.text_field :task_description, class: "form-control", id: "exampleInputEmail1" %>
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Task Deadline</label>
    <%= f.date_field :deadline, class: "form-control", id: "exampleInputEmail1" %>
  </div>

  <div class="mb-3">
      <%= f.number_field :user_id, id: :task_user_id, value: current_user.id, type: :hidden, class: "form-control", id: "exampleInputEmail1" %>
    </div>
  
  <p>
    <%= f.submit class: "btn btn-outline-success" %>
  </p>

  <p>
      <%= link_to "Cancel", category_tasks_path, class: "btn btn-outline-secondary" %>
  
  <% end %>

app/views/tasks/index.html.erb
<div class="col-md-8">
  <div class="row">
    <% @tasks.each do |task| %>
      <div class="col-md-6">
        <div class="card mt-3">
          <div class="card-body">
            <h3><%= task.task_name %></h3>
            <%= link_to 'View Task', category_task_path(task.category_id, task.id), class: "btn btn-primary" %> 
            <%= link_to 'Edit Task', edit_category_task_path(task.category_id, task.id), class: "btn btn-primary" %> 
            <%= link_to 'Delete Task', category_task_path(task.category_id, task.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>  
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</br>
<%= link_to 'Add New Task', new_category_task_path(@category), class: "btn btn-outline-success" %>
</br>
</br>
<%= link_to 'Back', categories_path, class: "btn btn-outline-secondary" %>

app/views/tasks/new.html.erb
<%= form_with scope: :task, model: [@task.category, @task], local: true do |f| %>

  <% if @task.errors.any? %>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
    <%end%>
  </ul>
  <%end%>

  <h1>Add Task</h1>

    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Task Name</label>
      <%= f.text_field :task_name, class: "form-control", id: "exampleInputEmail1" %>
    </div>

    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Task Description</label>
      <%= f.text_field :task_description, class: "form-control", id: "exampleInputEmail1" %>
    </div>

    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Task Deadline</label>
      <%= f.date_field :deadline, class: "form-control", id: "exampleInputEmail1" %>
    </div>

    <div class="mb-3">
      <%= f.number_field :user_id, id: :task_user_id, value: current_user.id, type: :hidden, class: "form-control", id: "exampleInputEmail1" %>
    </div>

    </br>
    <%= f.submit class: "btn btn-outline-success" %>
    <%= link_to "Cancel", category_tasks_path, class: "btn btn-outline-secondary" %>
  
  <% end %>

app/views/tasks/show.html.erb
<%= render @task%>